sudo: required
dist: focal
services:
  - docker
language: python
python:
  - "3.8"
addons:
  chrome: stable

before_install:
  - sudo apt-get install -yqq unzip
  - sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

  - docker build -f Dockerfile -t $DOCKER_REPO .
  - docker run -d -p 8000:80 $DOCKER_REPOM
  - docker ps
install:
  - pip install -r requirements.txt

script:

  - python3 test/test_views.py

after_success:
  - docker kill $DOCKER_REPO
  - sh .travis/deploy_dockerhub.sh
