sudo: required
dist: focal
services:
  - docker
language: python
python:
  - "3.8"
addons:
  chrome: stable

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get -y update
  - sudo apt-get install -y google-chrome-stable

  - sudo apt-get install -yqq unzip
  - sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

install:
  - pip install -r requirements.txt

script:
  - python3 test/test_views.py

after_success:
  - sh .travis/deploy_dockerhub.sh
