sudo: required
services:
  - docker
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

script:
  - python test/test_views.py

after_success:
  - sh .travis/deploy_dockerhub.sh
