version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        auth:
          username: alhas
          password: $DOCKER_PASS
        environment:
          FLASK_CONFIG: testing

    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python test/test_views.py

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and Push To DockerHub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            if ["$IMAGE_NAME" = "main"]; then
              TAG="latest"
            else
              TAG="$IMAGE_NAME"
            fi
            docker build -f Dockerfile -t $DOCKER_REPO
            sudo docker tag $DOCKER_REPO $DOCKER_REPOM
            sudo docker push $DOCKER_REPO:$TAG




